name: test build

on:
  push:
      branches:
        - test

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    #runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
          "GITHUB_REGISTRY_TOKEN=${{ secrets.REGISTRY_GITHUB_TOKEN }}"
          "VERSION=1.0.1"
          "REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}"
          "REACT_APP_APIV1_URL=${{ vars.REACT_APP_APIV1_URL }}"
          "REACT_APP_AUTH_URL=${{ vars.REACT_APP_AUTH_URL }}"
          "REACT_APP_CALLBACK_URL=${{ vars.REACT_APP_CALLBACK_URL }}"
          "REACT_APP_CLIENT_ID=${{ vars.REACT_APP_CLIENT_ID }}"
          "REACT_APP_TRADE_URL=${{ vars.REACT_APP_TRADE_URL }}"
          "REACT_APP_WAMP_REALM=${{ vars.REACT_APP_WAMP_REALM }}"
          "REACT_APP_WAMP_URL=${{ vars.REACT_APP_WAMP_URL }}"
          "REACT_APP_WEBWALLET_URL=${{ vars.REACT_APP_WEBWALLET_URL }}"
          "REACT_APP_LAUNCH_DARKLY_CLIENT_ID=${{ vars.REACT_APP_LAUNCH_DARKLY_CLIENT_ID }}
          "REACT_APP_KYC_URL=${{ vars.REACT_APP_KYC_URL }}"
          "REACT_APP_ENVIRONMENT=${{ vars.REACT_APP_ENVIRONMENT }}
        push: true
        tags: swisschains/lykkeexchangeweb:test
