name: test build

on:
  push:
      branches:
        - test

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
          "GITHUB_REGISTRY_TOKEN=${{ secrets.REGISTRY_GITHUB_TOKEN }}"
          "VERSION=1.0.1"
        push: true
        tags: swisschains/lykkeexchangeweb:test
