name: Release Service

on:
  push:
    tags: "service-*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Docker Name
      run: echo "DOCKER_IMAGE_NAME=$(echo lykkeexchangeweb)" >> $GITHUB_ENV
    - name: Show Docker Name
      run: echo DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME
    - name: Prepare Docker Tag
      run: echo "TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\/service-//")" >> $GITHUB_ENV
    - name: Show Docker Tag
      run: echo TAG=$TAG
    - name: Show Version from GITHUB_REF
      run: echo Version=${GITHUB_REF#refs/tags/service-}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Check if docker image exist
      run: if docker manifest inspect ${{ vars.DOCKER_IMAGE_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }} > /dev/null 2>&1;then echo Docker image ${{ vars.DOCKER_IMAGE_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }} already exist - Stop publishing!;exit 1;fi
    - name: Build and Publish
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
          "BUILD_VERSION=${{ env.TAG }}"
          "GITHUB_REGISTRY_TOKEN=${{ secrets.REGISTRY_GITHUB_TOKEN }}"
          "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}"
          "REACT_APP_APIV1_URL=${{ secrets.REACT_APP_APIV1_URL }}"
          "REACT_APP_AUTH_URL=${{ secrets.REACT_APP_AUTH_URL }}"
          "REACT_APP_CALLBACK_URL=${{ secrets.REACT_APP_CALLBACK_URL }}"
          "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}"
          "REACT_APP_TRADE_URL=${{ secrets.REACT_APP_TRADE_URL }}"
          "REACT_APP_WAMP_REALM=${{ secrets.REACT_APP_WAMP_REALM }}"
          "REACT_APP_WAMP_URL=${{ secrets.REACT_APP_WAMP_URL }}"
          "REACT_APP_WEBWALLET_URL=${{ secrets.REACT_APP_WEBWALLET_URL }}"
          "REACT_APP_LAUNCH_DARKLY_CLIENT_ID=${{ secrets.REACT_APP_LAUNCH_DARKLY_CLIENT_ID }}"
          "REACT_APP_KYC_URL=${{ secrets.REACT_APP_KYC_URL }}"
          "REACT_APP_ENVIRONMENT=${{ secrets.REACT_APP_ENVIRONMENT }}"`
        push: true
        tags: ${{ vars.DOCKER_IMAGE_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
